// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3JtyucYJc1Ec7_J0AVS8-0dJI6L1hEIo',
    appId: '1:556026602042:web:f41ea4cc5fe51d768c4b03',
    messagingSenderId: '556026602042',
    projectId: 'bebshar-poristhiti-stock-01',
    authDomain: 'bebshar-poristhiti-stock-01.firebaseapp.com',
    storageBucket: 'bebshar-poristhiti-stock-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGgAH2hIriqifHJ7BTAb52AqgjrhiIbNc',
    appId: '1:556026602042:android:9ca30a441f25ac4c8c4b03',
    messagingSenderId: '556026602042',
    projectId: 'bebshar-poristhiti-stock-01',
    storageBucket: 'bebshar-poristhiti-stock-01.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3JtyucYJc1Ec7_J0AVS8-0dJI6L1hEIo',
    appId: '1:556026602042:web:1e9a0cc30b4522478c4b03',
    messagingSenderId: '556026602042',
    projectId: 'bebshar-poristhiti-stock-01',
    authDomain: 'bebshar-poristhiti-stock-01.firebaseapp.com',
    storageBucket: 'bebshar-poristhiti-stock-01.firebasestorage.app',
  );
}
